### ISSUE TITLE
Publish to Hex.pm

### ISSUE THREAD

**Issue by waisbrot** [accense/eini#4]
I opened PR #3 to make this easier. I can also publish it for you if that's easier (or if nobody's home here).

**Comment by waisbrot** [comment]
I've published eini to Hex.pm. If you give me the email address(es) of the proper maintainers, I will set them as the package owners (and remove myself if you like).

**Comment by ghost** [comment]
Thank you for your publication. I don't worry about it.

**Comment by okeuday** [comment]
As described at https://github.com/erlcloud/erlcloud/issues/307 all the dependencies need to be hex.pm packages for dependant packages to be usable.

**Comment by waisbrot** [comment]
My PR #3 should take care of this, I think.

@tkojima are you maintaining this library? There's not much that needs changing, but I'd be happy to take it over or ask for it to come under erlcoud if you'd rather not keep watching it.

**Comment by okeuday** [comment]
@waisbrot @tkojima the "1.1.1-beta" tag no longer exists for proper, which impacts the https://github.com/accense/eini/pull/3 PR and the rebar.config file in the last hex.pm package, also, it is better to use `https://` prefixes for the deps to get fetched when compared to `git://` just due to proxy issues people have (not an issue I have)

**Comment by waisbrot** [comment]
Thanks for noticing. I'll fix that up. The main thing is that these are test dependencies so a normal Hex or Rebar3 user of the library should not be aware of those test deps.

**Comment by okeuday** [comment]
@waisbrot Yeah, it is good to switch them out to be test-only

**Comment by ghost** [comment]
@waisbrot Thanks.This project is no longer maintained, so I'm very happy you take it over.
